window.ARABIC_A1_BATCH2={schemaVersion:'2.0',course:'Arabic Structure Lab Living World',level:'A1',batch:'2/3',experienceRange:'51-100',experiences:[
['a1e051','👩🙂➡️👤','warmth','introduce_mother','هَذِهِ أُمِّي.','This is my mother.','こちらは母です。'],
['a1e052','👨🙂➡️👤','warmth','introduce_father','هَذَا أَبِي.','This is my father.','こちらは父です。'],
['a1e053','👦🙂👤','connection','family_brother','عِنْدِي أَخٌ.','I have a brother.','兄弟がいます。'],
['a1e054','👧🙂👤','connection','family_sister','عِنْدِي أُخْتٌ.','I have a sister.','姉妹がいます。'],
['a1e055','👀👫❓','concern','ask_friend_where','أَيْنَ صَدِيقِي؟','Where is my friend?','友達はどこですか？'],
['a1e056','🏠👤🙂','calm','friend_at_home','هُوَ فِي الْبَيْتِ.','He is at home.','彼は家にいます。'],
['a1e057','🙂❓👤','care','ask_wellbeing','كَيْفَ حَالُكَ؟','How are you?','元気ですか？'],
['a1e058','🙂👍','calm','say_fine','أَنَا بِخَيْرٍ.','I am fine.','元気です。'],
['a1e059','📱😌👫','affection','say_miss','أَشْتَاقُ إِلَيْكَ.','I miss you.','会いたいです。'],
['a1e060','🚪🙂🤲','warmth','welcome_guest','أَهْلًا وَسَهْلًا.','Welcome.','ようこそ。'],
['a1e061','⌚❓','curiosity','ask_time','كَمِ السَّاعَةُ؟','What time is it?','何時ですか？'],
['a1e062','🕖🙂','neutral','tell_time','السَّاعَةُ السَّابِعَةُ.','It is seven o’clock.','7時です。'],
['a1e063','📅👇💼','planning','today_work','الْيَوْمَ عِنْدِي عَمَلٌ.','I have work today.','今日は仕事があります。'],
['a1e064','📅➡️🙂','planning','tomorrow_free','غَدًا أَنَا حُرٌّ.','I am free tomorrow.','明日は暇です。'],
['a1e065','⬅️📅🏠','reflection','yesterday_home','أَمْسِ كُنْتُ فِي الْبَيْتِ.','I was at home yesterday.','昨日は家にいました。'],
['a1e066','👫⏰❓','interest','ask_when_meet','مَتَى نَلْتَقِي؟','When shall we meet?','いつ会いますか？'],
['a1e067','🕔🙂','agreement','meet_at_five','فِي السَّاعَةِ الْخَامِسَةِ.','At five o’clock.','5時に。'],
['a1e068','📱💼😕','busy','say_busy','أَنَا مَشْغُولٌ الْآنَ.','I am busy now.','今忙しいです。'],
['a1e069','⌚😐🤚','need','ask_wait','اِنْتَظِرْ قَلِيلًا.','Wait a little.','少し待って。'],
['a1e070','🚌➡️📍🙂','reassurance','arrive_soon','سَأَصِلُ قَرِيبًا.','I will arrive soon.','もうすぐ着きます。'],
['a1e071','🤒🏠','discomfort','say_sick','أَنَا مَرِيضٌ.','I am sick.','具合が悪いです。'],
['a1e072','😴😓🛏️','fatigue','say_tired','أَنَا مُتْعَبٌ.','I am tired.','疲れています。'],
['a1e073','🤕👉🧠','pain','say_headache','رَأْسِي يُؤْلِمُنِي.','My head hurts.','頭が痛いです。'],
['a1e074','🤢👉腹','pain','say_stomach','بَطْنِي يُؤْلِمُنِي.','My stomach hurts.','お腹が痛いです。'],
['a1e075','🤒👨‍⚕️❓','need','ask_doctor','أُرِيدُ طَبِيبًا.','I want a doctor.','医者をお願いします。'],
['a1e076','💊🏪❓','need','ask_pharmacy','أَيْنَ الصَّيْدَلِيَّةُ؟','Where is the pharmacy?','薬局はどこですか？'],
['a1e077','💊🙂🙏','need','ask_medicine','أُرِيدُ دَوَاءً.','I want medicine.','薬が欲しいです。'],
['a1e078','🤒💧🙏','need','request_water_health','أُرِيدُ مَاءً، مِنْ فَضْلِكَ.','I want water, please.','水をお願いします。'],
['a1e079','🛏️😌','fatigue','rest','أُرِيدُ أَنْ أَرْتَاحَ.','I want to rest.','休みたいです。'],
['a1e080','🙂👍🌤️','relief','say_better','أَنَا أَفْضَلُ الْآنَ.','I am better now.','今はよくなりました。'],
['a1e081','🧳🏨❓','uncertainty','ask_hotel','أَيْنَ الْفُنْدُقُ؟','Where is the hotel?','ホテルはどこですか？'],
['a1e082','🏨📄🙂','practical','say_reservation','لَدَيَّ حَجْزٌ.','I have a reservation.','予約があります。'],
['a1e083','📄👤🙂','neutral','give_name_booking','اِسْمِي عَلِيّ.','My name is Ali.','アリーです。'],
['a1e084','🔑🚪❓','curiosity','ask_room_number','مَا رَقْمُ الْغُرْفَةِ؟','What is the room number?','部屋番号は何番ですか？'],
['a1e085','🚪2️⃣0️⃣3️⃣','neutral','room_203','الْغُرْفَةُ رَقْمُ مِئَتَيْنِ وَثَلَاثَةٍ.','Room 203.','203号室です。'],
['a1e086','🛗❓','need','ask_elevator','أَيْنَ الْمِصْعَدُ؟','Where is the elevator?','エレベーターはどこですか？'],
['a1e087','🍳⏰❓','curiosity','ask_breakfast','مَتَى الْفُطُورُ؟','When is breakfast?','朝食は何時ですか？'],
['a1e088','🚿❌💧😕','problem','report_no_water','لَا يُوجَدُ مَاءٌ فِي الْغُرْفَةِ.','There is no water in the room.','部屋に水がありません。'],
['a1e089','📶❓','need','ask_wifi','هَلْ يُوجَدُ وَاي فَاي؟','Is there Wi-Fi?','Wi-Fiはありますか？'],
['a1e090','📶🔐❓','need','ask_password','مَا كَلِمَةُ الْمُرُورِ؟','What is the password?','パスワードは何ですか？'],
['a1e091','👂🤔❓','confusion','say_dont_understand','لَا أَفْهَمُ.','I do not understand.','分かりません。'],
['a1e092','👂🔁🙏','need','ask_again','مَرَّةً أُخْرَى، مِنْ فَضْلِكَ.','Again, please.','もう一度お願いします。'],
['a1e093','👂🐢🙏','need','ask_slow','بِبُطْءٍ، مِنْ فَضْلِكَ.','Slowly, please.','ゆっくりお願いします。'],
['a1e094','🗺️😟','anxiety','say_lost','أَنَا تَائِهٌ.','I am lost.','道に迷いました。'],
['a1e095','🆘👀🙏','need','ask_help','سَاعِدْنِي، مِنْ فَضْلِكَ.','Help me, please.','助けてください。'],
['a1e096','🍽️❌😕','disappointment','report_wrong','هَذَا لَيْسَ طَلَبِي.','This is not my order.','これは私の注文ではありません。'],
['a1e097','📱💥😕','frustration','say_broken','هَاتِفِي لَا يَعْمَلُ.','My phone does not work.','電話が動きません。'],
['a1e098','🚪🔒😕','disappointment','read_closed','الْمَحَلُّ مُغْلَقٌ.','The shop is closed.','店は閉まっています。'],
['a1e099','🚪🔓🙂','relief','read_open','الْمَحَلُّ مَفْتُوحٌ.','The shop is open.','店は開いています。'],
['a1e100','👛❌😧🔍','panic','lost_wallet','لَا أَجِدُ مِحْفَظَتِي.','I cannot find my wallet.','財布が見つかりません。']
].map((x,n)=>({id:x[0],number:51+n,theme:n<10?'family':n<20?'time':n<30?'health':n<40?'hotel':'problems',scene:{mentalScene:x[1]},mind:{emotionOrBodyState:x[2],communicativeIntent:x[3]},languageEmergence:{utterance:{ar:x[4],en:x[5],ja:x[6]},vocalizationPolicy:'manual_button_only'},interaction:{skills:['listening','speaking','reading','writing'],supportOrder:['scene','audio','script','en','ja','analysis'],consequence:'world_continues'},memory:{type:n%3===0?'discovery':'reencounter'},analysisRef:{enabled:true,layers:['wordAnatomy','chunks','sentenceArchitecture','irab']},cefr:'A1'}))};