window.ARABIC_A1_BATCH1={schemaVersion:'2.0',course:'Arabic Structure Lab Living World',level:'A1',batch:'1/3',experienceRange:'1-50',experiences:[
['a1e001','👀 → 🙂 → 👋','warm curiosity','greet','مَرْحَبًا','Hello','こんにちは'],
['a1e002','👤❓ → 🙂','curiosity','ask_name','مَا اسْمُكَ؟','What is your name?','お名前は？'],
['a1e003','🙂🗣️','openness','say_name','اِسْمِي عَلِيّ.','My name is Ali.','私はアリーです。'],
['a1e004','🌍❓','curiosity','ask_origin','مِنْ أَيْنَ أَنْتَ؟','Where are you from?','どこの出身ですか？'],
['a1e005','🇯🇵🙂','calm','say_origin','أَنَا مِنَ الْيَابَانِ.','I am from Japan.','私は日本出身です。'],
['a1e006','🌅🙂👋','pleasant','morning_greeting','صَبَاحُ الْخَيْرِ.','Good morning.','おはようございます。'],
['a1e007','🚿 → 👕 → 👟 → 🙂','readiness','say_ready','أَنَا جَاهِزٌ.','I am ready.','準備できました。'],
['a1e008','🔑❓ → 😕 → 🔍','concern','find_key','أَيْنَ الْمِفْتَاحُ؟','Where is the key?','鍵はどこ？'],
['a1e009','🔑 → 🪑👇 → 😮','relief','locate_object','الْمِفْتَاحُ عَلَى الْكُرْسِيِّ.','The key is on the chair.','鍵は椅子の上です。'],
['a1e010','🙏🙂','gratitude','thank','شُكْرًا.','Thank you.','ありがとう。'],
['a1e011','☀️ → 🚶 → 🥵 → 💧👀','thirst','request_water','أُرِيدُ مَاءً.','I want water.','水が欲しいです。'],
['a1e012','👨‍🍳🙂 → ❓','attention','ask_want','مَاذَا تُرِيدُ؟','What do you want?','何が欲しいですか？'],
['a1e013','🥤❓ ↔️ 🧃❓','choice','offer_choice','مَاءٌ أَمْ عَصِيرٌ؟','Water or juice?','水、それともジュース？'],
['a1e014','🧃🙂🙏','desire','order_juice','عَصِيرٌ، مِنْ فَضْلِكَ.','Juice, please.','ジュースをお願いします。'],
['a1e015','🍽️😣 → 👀🍞','hunger','say_hungry','أَنَا جَائِعٌ.','I am hungry.','お腹が空いています。'],
['a1e016','🍞🧀🙂','desire','order_food','أُرِيدُ خُبْزًا وَجُبْنًا.','I want bread and cheese.','パンとチーズが欲しいです。'],
['a1e017','🍽️ → 😋👍','pleasure','praise_food','الطَّعَامُ لَذِيذٌ.','The food is delicious.','食べ物がおいしいです。'],
['a1e018','☕🔥 → 😖','surprise','describe_hot','الْقَهْوَةُ سَاخِنَةٌ.','The coffee is hot.','コーヒーは熱いです。'],
['a1e019','💧🧊 → 🙂','refreshment','describe_cold','الْمَاءُ بَارِدٌ.','The water is cold.','水は冷たいです。'],
['a1e020','🍽️ → 💳❓','practical need','ask_bill','الْحِسَابُ، مِنْ فَضْلِكَ.','The bill, please.','お会計をお願いします。'],
['a1e021','👕👀 → 🙂','interest','want_this','أُرِيدُ هَذَا.','I want this.','これが欲しいです。'],
['a1e022','🏷️❓','curiosity','ask_price','كَمْ هَذَا؟','How much is this?','これはいくらですか？'],
['a1e023','🏷️😕','concern','describe_expensive','هَذَا غَالٍ.','This is expensive.','これは高いです。'],
['a1e024','🔵👕🙂','pleasure','describe_blue','لَوْنُهُ أَزْرَقُ.','It is blue.','青色です。'],
['a1e025','👕🪞❓','uncertainty','ask_try','هَلْ أَسْتَطِيعُ أَنْ أُجَرِّبَهُ؟','Can I try it?','試着できますか？'],
['a1e026','🛍️🙂','decision','buy','سَآخُذُهُ.','I will take it.','これにします。'],
['a1e027','🚉❓ → 😕','uncertainty','ask_station','أَيْنَ الْمَحَطَّةُ؟','Where is the station?','駅はどこですか？'],
['a1e028','🚶➡️','helpfulness','direction_straight','اِذْهَبْ مُسْتَقِيمًا.','Go straight.','まっすぐ行ってください。'],
['a1e029','🚶↪️','helpfulness','turn_right','اِنْعَطِفْ يَمِينًا.','Turn right.','右に曲がってください。'],
['a1e030','🚆❓ → ⏰😟','urgency','ask_platform','أَيْنَ الرَّصِيفُ؟','Where is the platform?','ホームはどこですか？'],
['a1e031','🚌📱','calm','say_on_bus','أَنَا فِي الْحَافِلَةِ.','I am on the bus.','バスの中です。'],
['a1e032','⏰ → 🚌💨 → 😱','panic','say_late','تَأَخَّرْتُ.','I am late.','遅れました。'],
['a1e033','🎫❓','need','ask_ticket','أُرِيدُ تَذْكِرَةً.','I want a ticket.','切符が欲しいです。'],
['a1e034','🚪➡️❓','uncertainty','ask_exit','أَيْنَ الْخُرُوجُ؟','Where is the exit?','出口はどこですか？'],
['a1e035','👫🙂','warmth','introduce_friend','هَذَا صَدِيقِي.','This is my friend.','こちらは私の友達です。'],
['a1e036','👨‍👩‍👧‍👦🙂','warmth','talk_family','هَذِهِ عَائِلَتِي.','This is my family.','こちらは私の家族です。'],
['a1e037','🙂❓','care','ask_wellbeing','كَيْفَ حَالُكَ؟','How are you?','元気ですか？'],
['a1e038','🙂👍','calm','say_fine','أَنَا بِخَيْرٍ.','I am fine.','元気です。'],
['a1e039','⏰❓','curiosity','ask_time','كَمِ السَّاعَةُ؟','What time is it?','何時ですか？'],
['a1e040','👫 → 🕔','agreement','meet_at_five','فِي السَّاعَةِ الْخَامِسَةِ.','At five o’clock.','5時に。'],
['a1e041','📱💼😕','busy','say_busy','أَنَا مَشْغُولٌ الْآنَ.','I am busy now.','今忙しいです。'],
['a1e042','⌚😐','need','ask_wait','اِنْتَظِرْ قَلِيلًا.','Wait a little.','少し待って。'],
['a1e043','🤒🏠','discomfort','say_sick','أَنَا مَرِيضٌ.','I am sick.','具合が悪いです。'],
['a1e044','🤒 → 👨‍⚕️❓','need','ask_doctor','أُرِيدُ طَبِيبًا.','I want a doctor.','医者をお願いします。'],
['a1e045','💊❓','need','ask_pharmacy','أَيْنَ الصَّيْدَلِيَّةُ؟','Where is the pharmacy?','薬局はどこですか？'],
['a1e046','🧳 → 🏨❓','uncertainty','ask_hotel','أَيْنَ الْفُنْدُقُ؟','Where is the hotel?','ホテルはどこですか？'],
['a1e047','🏨📄🙂','practical','say_reservation','لَدَيَّ حَجْزٌ.','I have a reservation.','予約があります。'],
['a1e048','🔑🚪❓','curiosity','ask_room_number','مَا رَقْمُ الْغُرْفَةِ؟','What is the room number?','部屋番号は何番ですか？'],
['a1e049','👂🤔❓','confusion','say_dont_understand','لَا أَفْهَمُ.','I do not understand.','分かりません。'],
['a1e050','👂🔁🙏','need','ask_again','مَرَّةً أُخْرَى، مِنْ فَضْلِكَ.','Again, please.','もう一度お願いします。']
].map(x=>({id:x[0],scene:{mentalScene:x[1]},mind:{emotionOrBodyState:x[2],communicativeIntent:x[3]},languageEmergence:{utterance:{ar:x[4],en:x[5],ja:x[6]},vocalizationPolicy:'manual_button_only'}}))};