window.ARABIC_A1_BATCH3={schemaVersion:'2.0',course:'Arabic Structure Lab Living World',level:'A1',batch:'3/3',experienceRange:'101-150',experiences:[
['a1e101','☕🙂','pleasure','like_coffee','أُحِبُّ الْقَهْوَةَ.','I like coffee.','コーヒーが好きです。'],
['a1e102','🍵😐','mild dislike','dont_like_tea','لَا أُحِبُّ الشَّايَ.','I do not like tea.','お茶は好きではありません。'],
['a1e103','☕↔️🍵🤔','preference','prefer_coffee','أُفَضِّلُ الْقَهْوَةَ.','I prefer coffee.','コーヒーの方が好きです。'],
['a1e104','🏙️😍','pleasure','like_city','أُحِبُّ هَذِهِ الْمَدِينَةَ.','I like this city.','この街が好きです。'],
['a1e105','🎁😮😊','joy','say_happy','أَنَا سَعِيدٌ.','I am happy.','うれしいです。'],
['a1e106','🌧️😔','sadness','say_sad','أَنَا حَزِينٌ.','I am sad.','悲しいです。'],
['a1e107','⌚📱😟','worry','say_worried','أَنَا قَلِقٌ.','I am worried.','心配です。'],
['a1e108','🌙😨','fear','say_afraid','أَنَا خَائِفٌ.','I am afraid.','怖いです。'],
['a1e109','😮🎁','surprise','say_surprised','أَنَا مُتَفَاجِئٌ.','I am surprised.','驚いています。'],
['a1e110','💡🙂👍','approval','good_idea','فِكْرَةٌ جَيِّدَةٌ.','Good idea.','いい考えです。'],
['a1e111','🙂❓💬','curiosity','ask_opinion','مَا رَأْيُكَ؟','What do you think?','どう思いますか？'],
['a1e112','🙂💬👍','confidence','simple_opinion','أَعْتَقِدُ أَنَّهُ جَيِّدٌ.','I think it is good.','いいと思います。'],
['a1e113','☀️🌿🙂','contentment','weather_beautiful','الْجَوُّ جَمِيلٌ الْيَوْمَ.','The weather is beautiful today.','今日はいい天気です。'],
['a1e114','🌧️☂️','attention','weather_rain','تُمْطِرُ الْيَوْمَ.','It is raining today.','今日は雨です。'],
['a1e115','🥵☀️','heat','weather_hot','الْجَوُّ حَارٌّ.','The weather is hot.','暑いです。'],
['a1e116','🥶🧥','cold','weather_cold','الْجَوُّ بَارِدٌ.','The weather is cold.','寒いです。'],
['a1e117','🌬️🧣','cold','need_jacket','أَحْتَاجُ إِلَى مِعْطَفٍ.','I need a coat.','コートが必要です。'],
['a1e118','🌧️☂️❌','need','need_umbrella','أَحْتَاجُ إِلَى مِظَلَّةٍ.','I need an umbrella.','傘が必要です。'],
['a1e119','☀️🚶🙂','anticipation','go_out','سَأَخْرُجُ الْيَوْمَ.','I will go out today.','今日は出かけます。'],
['a1e120','🌧️🏠😌','calm','stay_home','سَأَبْقَى فِي الْبَيْتِ.','I will stay at home.','家にいます。'],
['a1e121','📱🔔👀','attention','read_message','عِنْدِي رِسَالَةٌ.','I have a message.','メッセージがあります。'],
['a1e122','📱✍️🙂','purpose','write_message','سَأَكْتُبُ رِسَالَةً.','I will write a message.','メッセージを書きます。'],
['a1e123','📞🙂❓','connection','call_friend','هَلْ أَسْتَطِيعُ أَنْ أَتَّصِلَ بِكَ؟','Can I call you?','電話してもいいですか？'],
['a1e124','📱🔇🤔','confusion','cant_hear','لَا أَسْمَعُكَ جَيِّدًا.','I cannot hear you well.','よく聞こえません。'],
['a1e125','📱🔁🙏','need','say_again','قُلْهَا مَرَّةً أُخْرَى، مِنْ فَضْلِكَ.','Say it again, please.','もう一度言ってください。'],
['a1e126','📱🐢👂','need','speak_slowly','تَكَلَّمْ بِبُطْءٍ، مِنْ فَضْلِكَ.','Speak slowly, please.','ゆっくり話してください。'],
['a1e127','📶❌😕','frustration','no_internet','لَا يُوجَدُ إِنْتَرْنِت.','There is no internet.','インターネットがありません。'],
['a1e128','🔋1️⃣% 😟','urgency','charge_phone','أَحْتَاجُ إِلَى شَاحِنٍ.','I need a charger.','充電器が必要です。'],
['a1e129','🌅📅🤔','planning','plan_day','مَاذَا سَأَفْعَلُ الْيَوْمَ؟','What will I do today?','今日は何をしよう？'],
['a1e130','☕🚶🙂','anticipation','go_cafe','سَأَذْهَبُ إِلَى الْمَقْهَى.','I will go to the café.','カフェへ行きます。'],
['a1e131','📱👫🙂','warmth','invite_friend','هَلْ تُرِيدُ أَنْ تَأْتِيَ؟','Do you want to come?','来ませんか？'],
['a1e132','🙂👍','pleasure','agree','نَعَمْ، بِكُلِّ سُرُورٍ.','Yes, with pleasure.','はい、喜んで。'],
['a1e133','😕📅','regret','decline','آسِفٌ، لَا أَسْتَطِيعُ الْيَوْمَ.','Sorry, I cannot today.','すみません、今日は無理です。'],
['a1e134','☕🍽️🤔','consideration','choose_place','أَيْنَ نَلْتَقِي؟','Where shall we meet?','どこで会いますか？'],
['a1e135','🕔🕕🤔','consideration','choose_time','هَلِ السَّاعَةُ الْخَامِسَةُ مُنَاسِبَةٌ؟','Is five o’clock suitable?','5時でいいですか？'],
['a1e136','⏰😰📱','regret','message_late','آسِفٌ، سَأَتَأَخَّرُ قَلِيلًا.','Sorry, I will be a little late.','すみません、少し遅れます。'],
['a1e137','👀👋🙂','relief','arrive_meet','هَا أَنَا ذَا!','Here I am!','来ました！'],
['a1e138','☕🍰👫','pleasure','order_together','نُرِيدُ قَهْوَتَيْنِ، مِنْ فَضْلِكَ.','We want two coffees, please.','コーヒーを2つお願いします。'],
['a1e139','🍰😋','pleasure','like_cake','هَذِهِ الْكَعْكَةُ لَذِيذَةٌ.','This cake is delicious.','このケーキはおいしいです。'],
['a1e140','💳🙂','practical','pay_together','سَأَدْفَعُ الْحِسَابَ.','I will pay the bill.','会計を払います。'],
['a1e141','⬅️📅🛒💬','reflection','talk_yesterday','أَمْسِ ذَهَبْتُ إِلَى السُّوقِ.','Yesterday I went to the market.','昨日、市場へ行きました。'],
['a1e142','🛒🍎🥖','recollection','bought_food','اِشْتَرَيْتُ فَاكِهَةً وَخُبْزًا.','I bought fruit and bread.','果物とパンを買いました。'],
['a1e143','➡️📅👫','planning','talk_tomorrow','غَدًا سَأَزُورُ صَدِيقِي.','Tomorrow I will visit my friend.','明日、友達を訪ねます。'],
['a1e144','🏠🍽️👫','hospitality','invite_dinner','تَعَالَ لِنَأْكُلَ مَعًا.','Come, let us eat together.','一緒に食べましょう。'],
['a1e145','🚉🗺️🙂','confidence','find_way','الْآنَ أَعْرِفُ الطَّرِيقَ.','Now I know the way.','もう道が分かります。'],
['a1e146','👂🗣️🙂','confidence','understand_more','أَفْهَمُ أَكْثَرَ الْآنَ.','I understand more now.','今はもっと分かります。'],
['a1e147','📖👀🤔','curiosity','read_arabic','أَقْرَأُ بِالْعَرَبِيَّةِ قَلِيلًا.','I read a little in Arabic.','アラビア語で少し読みます。'],
['a1e148','✍️📱🙂','confidence','write_arabic','أَكْتُبُ رِسَالَةً بِالْعَرَبِيَّةِ.','I write a message in Arabic.','アラビア語でメッセージを書きます。'],
['a1e149','🗣️👫🙂','confidence','speak_arabic','أَتَكَلَّمُ الْعَرَبِيَّةَ قَلِيلًا.','I speak a little Arabic.','アラビア語を少し話します。'],
['a1e150','🌇☕🙂👋','contentment','close_day','كَانَ يَوْمًا جَمِيلًا.','It was a nice day.','いい一日でした。']
].map((x,n)=>({id:x[0],number:101+n,theme:n<12?'feelings':n<20?'weather':n<28?'communication':n<40?'independent_life':'integration',scene:{mentalScene:x[1]},mind:{emotionOrBodyState:x[2],communicativeIntent:x[3]},languageEmergence:{utterance:{ar:x[4],en:x[5],ja:x[6]},vocalizationPolicy:'manual_button_only'},interaction:{skills:['listening','speaking','reading','writing'],supportOrder:['scene','audio','script','en','ja','analysis'],consequence:'world_continues'},memory:{type:n%4===0?'discovery':'reencounter'},analysisRef:{enabled:true,layers:['wordAnatomy','chunks','sentenceArchitecture','irab']},cefr:'A1'}))};