(function(){
const LEVELK='asl.course.level.v1',levels=['A1','A2','B1','B2','C1','C2'];
let level=localStorage.getItem(LEVELK)||'A1',ci=0,stage=0,items=[],chapters=[];
const $q=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const posKey=()=>`asl.course.pos.${level}.v1`;
function loadScript(src){return new Promise((ok,bad)=>{const existing=[...document.scripts].find(s=>new URL(s.src||'',location.href).pathname.endsWith(src.replace('./','/'))||s.dataset.courseSrc===src);if(existing){if(src.includes('a1-batch1')&&window.ARABIC_A1_BATCH1)return ok();if(src.includes('a1-batch2')&&window.ARABIC_A1_BATCH2)return ok();if(src.includes('a1-batch3')&&window.ARABIC_A1_BATCH3)return ok();if(src.includes('a1-expansion')&&window.ARABIC_A1_EXPANSION)return ok();if(src.includes('a1-chapters')&&window.ARABIC_A1_CHAPTERS)return ok();if(src.includes('cefr-curriculum')&&window.ARABIC_CEFR_LEVELS)return ok();if(existing.dataset.courseSrc===src)return ok();}const s=document.createElement('script');s.src=src;s.dataset.courseSrc=src;s.onload=ok;s.onerror=bad;document.head.appendChild(s)})}
async function ensureBase(){for(const f of ['./a1-batch1.js','./a1-batch2.js','./a1-batch3.js','./a1-expansion.js','./a1-chapters.js','./cefr-curriculum.js','./deep-analysis-audited.js']){try{await loadScript(f)}catch(e){console.warn('Course asset failed',f,e)}}}
function setLevelData(){
 if(level==='A1'){
  const batches=[window.ARABIC_A1_BATCH1,window.ARABIC_A1_BATCH2,window.ARABIC_A1_BATCH3,window.ARABIC_A1_EXPANSION].filter(Boolean);
  items=batches.flatMap(b=>b.experiences||[]).map((r,i)=>({id:r[0],scene:r[1],emotion:r[2],intent:r[3],ar:r[4],en:r[5],ja:r[6],index:i}));chapters=window.ARABIC_A1_CHAPTERS||[];
 }else{
  const d=window.ARABIC_CEFR_LEVELS?.[level];items=(d?.experiences||[]).map((r,i)=>({id:r[0],scene:r[1],emotion:r[2],intent:r[3],ar:r[4],en:r[5],ja:r[6],index:i}));chapters=d?.chapters||[];
 }
 ci=Math.max(0,Math.min(+(localStorage.getItem(posKey())||0),Math.max(0,items.length-1)));
}
function chapterFor(index){const n=index+1;return chapters.find(c=>n>=c.start&&n<=c.end)||{id:level,start:1,end:items.length,emoji:'🌍',titleEn:`Arabic ${level}`,titleJa:`アラビア語 ${level}`,worldEn:'',worldJa:''}}
function speak(text,rate=.78){return window.ARABIC_AUDIO_SERVICE?.speak?.(text,{rate})||false}
function cleanWord(t){return String(t||'').replace(/^[«“\[(]+|[.،؟!?؛:»”\])]+$/g,'').trim()}
function words(ar){return String(ar||'').split(/\s+/).map(cleanWord).filter(Boolean)}
function sentenceHtml(ar){return String(ar||'').split(/(\s+)/).map(part=>{if(!part)return'';if(/^\s+$/.test(part))return part;const w=cleanWord(part);if(!w)return esc(part);const at=part.indexOf(w),before=at>=0?part.slice(0,at):'',after=at>=0?part.slice(at+w.length):'';return `${esc(before)}<button type="button" class="courseWord courseSentenceWord" data-course-word="${esc(w)}" data-speak-ar="${esc(w)}">${esc(w)}</button>${esc(after)}`}).join('')}
const css=document.createElement('style');css.textContent=`#courseModal{display:none;position:fixed;z-index:120;inset:0;background:#f5f2ea;overflow:auto}#courseModal.show{display:block}.courseIn{max-width:720px;margin:auto;padding:18px 14px 110px}.courseTop{display:flex;justify-content:space-between;align-items:center;gap:10px}.courseCard{margin-top:16px;background:#fffdf8;border:1px solid #ded9ce;border-radius:28px;padding:22px;box-shadow:0 12px 34px #0000000a}.courseScene{text-align:center;font-size:42px;line-height:1.65;background:#f0eee7;border-radius:22px;padding:18px 8px}.courseArabic{direction:rtl;text-align:center;font:clamp(32px,8vw,52px)/1.8 "Geeza Pro","Noto Naskh Arabic",serif;margin:18px 0}.courseSentenceWord{border:0!important;background:transparent!important;border-radius:8px!important;padding:0 2px!important;font:inherit!important;color:inherit!important;line-height:inherit!important;vertical-align:baseline}.courseSentenceWord.cwdActive{background:#eef5f2!important;box-shadow:0 0 0 2px rgba(31,111,97,.18)}.courseStage{border-top:1px solid #eee7dc;margin-top:15px;padding-top:15px}.courseLabel{font-size:10px;color:#75807c;letter-spacing:.08em;text-transform:uppercase}.courseEn{font-size:20px;font-weight:760;margin-top:6px}.courseJa{font-size:12px;color:#75807c;margin-top:4px}.courseWords{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px;direction:rtl}.courseWord:not(.courseSentenceWord){border:1px solid #ded9ce;background:#fff;border-radius:999px;padding:10px 13px;font:20px "Geeza Pro",serif}.courseNext{width:100%;border:0;background:#1f6f61;color:white;border-radius:16px;padding:14px;font-weight:780;margin-top:18px}.courseActions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.courseBtn{border:1px solid #ded9ce;background:#fff;border-radius:14px;padding:10px 12px}.courseProgress{font-size:12px;color:#75807c}.courseChapter{margin-top:14px;background:#20302d;color:#fff;border-radius:22px;padding:16px}.courseChapterTop{display:flex;align-items:center;gap:11px}.courseChapterEmoji{font-size:32px}.courseChapterTitle{font-size:18px;font-weight:800}.courseChapterJa{font-size:12px;color:#cdd7d4}.courseChapterStory{font-size:13px;line-height:1.55;color:#e8efed;margin-top:10px}.courseSelect{width:100%;margin-top:10px;border:0;border-radius:12px;padding:10px;background:#fff;color:#20302d;font-weight:700}.levelbar{display:grid;grid-template-columns:repeat(6,1fr);gap:5px;margin-top:14px}.levelbtn{border:1px solid #d9d4ca;background:#fff;border-radius:12px;padding:9px 4px;font-weight:800}.levelbtn.on{background:#1f6f61;color:#fff;border-color:#1f6f61}@media(max-width:430px){.levelbar{grid-template-columns:repeat(3,1fr)}}`;
document.head.appendChild(css);
const modal=document.createElement('section');modal.id='courseModal';modal.innerHTML='<div class="courseIn"><div class="courseTop"><div><b>Arabic Course</b><div class="courseProgress" id="courseProgress"></div></div><button class="courseBtn" id="courseClose">×</button></div><div class="levelbar" id="courseLevels"></div><div id="courseBody"></div></div>';document.body.appendChild(modal);
function howText(){const generic={A1:['Notice how the words express the scene before naming the grammar.','文法名より先に、場面と言葉の結びつきに注目します。'],A2:['Notice how time, sequence and simple reasons extend the message.','時間・順序・簡単な理由が文を広げる仕組みに注目します。'],B1:['Follow how clauses connect events, reasons, conditions and decisions.','出来事・理由・条件・決定が節でどうつながるかを見ます。'],B2:['Track qualification, contrast, evidence and competing viewpoints.','限定・対比・根拠・異なる観点の組み立てを追います。'],C1:['Track framing, stance, uncertainty and abstract causal structure.','枠組み・立場・不確実性・抽象的因果構造を追います。'],C2:['Track implication, register, rhetoric, perspective and stylistic force.','含意・レジスター・修辞・視点・文体的効果を追います。']};return generic[level]}
function levelBar(){return levels.map(l=>`<button class="levelbtn ${l===level?'on':''}" data-level="${l}">${l}</button>`).join('')}
function chapterHtml(ch){const opt=chapters.map(c=>`<option value="${c.start-1}" ${c.id===ch.id?'selected':''}>${esc(c.id)} · ${esc(c.titleEn)} / ${esc(c.titleJa)}</option>`).join('');return `<section class="courseChapter"><div class="courseChapterTop"><div class="courseChapterEmoji">${esc(ch.emoji)}</div><div><div class="courseLabel" style="color:#aebfba">${esc(ch.id)} · ${ch.start}–${ch.end}</div><div class="courseChapterTitle">${esc(ch.titleEn)}</div><div class="courseChapterJa">${esc(ch.titleJa)}</div></div></div><div class="courseChapterStory">${esc(ch.worldEn||'')}<br><span style="color:#cdd7d4">${esc(ch.worldJa||'')}</span></div><select class="courseSelect" id="courseChapterSelect">${opt}</select></section>`}
function render(){const x=items[ci];$q('#courseLevels').innerHTML=levelBar();document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{level=b.dataset.level;localStorage.setItem(LEVELK,level);stage=0;setLevelData();render()});if(!x){$q('#courseProgress').textContent=`${level} · 0 Experiences`;$q('#courseBody').innerHTML='<div class="courseCard"><b>Course data could not be loaded.</b><div class="courseJa">Reload once. A1 remains part of the built-in course and is not deleted.</div></div>';return}const ch=chapterFor(ci),within=ci-ch.start+2;$q('#courseProgress').textContent=`${ch.id} · ${within}/${ch.end-ch.start+1} · Overall ${ci+1}/${items.length}`;let h=chapterHtml(ch)+`<div class="courseCard"><div class="courseLabel">Mental Scene</div><div class="courseScene">${esc(x.scene)}</div><div class="courseActions"><button class="courseBtn" id="courseListen">▶ Listen first</button></div>`;
if(stage>=1)h+=`<div class="courseStage"><div class="courseLabel">Arabic · tap any word</div><div class="courseArabic">${sentenceHtml(x.ar)}</div><div class="courseActions"><button class="courseBtn" id="courseReplay">▶ Replay</button></div></div>`;
if(stage>=2)h+=`<div class="courseStage"><div class="courseLabel">Meaning</div><div class="courseEn">${esc(x.en)}</div><div class="courseJa">${esc(x.ja)}</div></div>`;
if(stage>=3)h+=`<div class="courseStage"><div class="courseLabel">Words · tap for full word analysis</div><div class="courseWords">${words(x.ar).map(w=>`<button class="courseWord" data-course-word="${esc(w)}" data-speak-ar="${esc(w)}">${esc(w)} 🔊</button>`).join('')}</div></div>`;
if(stage>=4){const t=howText();h+=`<div class="courseStage"><div class="courseLabel">How it works</div><div class="courseEn">${esc(t[0])}</div><div class="courseJa">${esc(t[1])}</div></div>`}
if(stage>=5){const deepButton=level==='A1'?'<button class="courseBtn" id="courseDeep" style="margin-top:10px">Open Human-reviewed Deep Analysis ›</button>':'<button class="courseBtn" id="courseDeepAudited" style="margin-top:10px">Open Audited Deep Analysis ›</button>';h+=`<div class="courseStage"><div class="courseLabel">Deep Arabic</div><div class="courseEn">Word Anatomy · Root / Pattern · Morphology · Grammar · إعراب · Discourse / Register</div><div class="courseJa">監修辞書を優先し、不確かな語根・派生形は推測せず not asserted と表示します。</div>${deepButton}</div>`}
const labels=['Show Arabic ›','Show meaning ›','Show words ›','How it works ›','Deep Arabic ›','Next Experience ›'];h+=`<button class="courseNext" id="courseNext">${labels[Math.min(stage,5)]}</button><div class="courseActions"><button class="courseBtn" id="coursePrev">‹ Previous</button><button class="courseBtn" id="courseReset">Start again</button></div></div>`;$q('#courseBody').innerHTML=h;
$q('#courseChapterSelect').onchange=e=>{ci=+e.target.value;stage=0;localStorage.setItem(posKey(),String(ci));render()};$q('#courseListen').onclick=()=>speak(x.ar,.72);$q('#courseReplay')?.addEventListener('click',()=>speak(x.ar,.72));$q('#courseDeep')?.addEventListener('click',()=>{localStorage.setItem('asl.a1.pos',String(ci));location.href='./living.html'});$q('#courseDeepAudited')?.addEventListener('click',()=>{if(typeof window.ARABIC_DEEP_OPEN==='function')window.ARABIC_DEEP_OPEN(x.ar,level)});$q('#courseNext').onclick=()=>{if(stage<5){stage++;render()}else{ci=Math.min(items.length-1,ci+1);stage=0;localStorage.setItem(posKey(),String(ci));render()}};$q('#coursePrev').onclick=()=>{ci=Math.max(0,ci-1);stage=0;localStorage.setItem(posKey(),String(ci));render()};$q('#courseReset').onclick=()=>{stage=0;render()};}
async function openCourse(forceLevel){if(forceLevel){level=forceLevel;localStorage.setItem(LEVELK,level)}await ensureBase();setLevelData();stage=0;render();modal.classList.add('show')}
$q('#courseClose').onclick=()=>modal.classList.remove('show');const top=document.querySelector('.top');if(top){const a1=document.createElement('button');a1.className='btn';a1.textContent='A1 Course';a1.id='a1CourseOpen';const general=document.createElement('button');general.className='btn';general.textContent='Course';general.id='courseOpen';const add=document.querySelector('#add');top.insertBefore(a1,add||null);top.insertBefore(general,add||null);a1.onclick=()=>openCourse('A1');general.onclick=()=>openCourse()}
window.ARABIC_COURSE_OPEN=openCourse;
})();