(function(){
const POS='asl.course.pos.v1';
let ci=Math.max(0,+(localStorage.getItem(POS)||0)),stage=0,items=[],chapters=[];
const $q=s=>document.querySelector(s);
const esc2=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function loadScript(src){return new Promise((ok,bad)=>{if(document.querySelector(`script[data-course-src="${src}"]`))return ok();const s=document.createElement('script');s.src=src;s.dataset.courseSrc=src;s.onload=ok;s.onerror=bad;document.head.appendChild(s)})}
async function ensureData(){
  for(const f of ['./a1-batch1.js','./a1-batch2.js','./a1-batch3.js','./a1-expansion.js','./a1-chapters.js']){try{await loadScript(f)}catch(e){}}
  const batches=[window.ARABIC_A1_BATCH1,window.ARABIC_A1_BATCH2,window.ARABIC_A1_BATCH3,window.ARABIC_A1_EXPANSION].filter(Boolean);
  items=batches.flatMap(b=>b.experiences||[]).map((r,i)=>({id:r[0],scene:r[1],emotion:r[2],intent:r[3],ar:r[4],en:r[5],ja:r[6],index:i}));
  chapters=window.ARABIC_A1_CHAPTERS||[];
  ci=Math.min(ci,Math.max(0,items.length-1));
}
function chapterFor(index){const n=index+1;return chapters.find(c=>n>=c.start&&n<=c.end)||{id:'A1',start:1,end:items.length,emoji:'🌍',titleEn:'Arabic A1',titleJa:'アラビア語A1',worldEn:'',worldJa:''}}
function speak(text,rate=.78){if(!text||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ar-SA';u.rate=rate;try{const v=speechSynthesis.getVoices().find(x=>/^ar(-|$)/i.test(x.lang||''));if(v)u.voice=v}catch(e){}speechSynthesis.speak(u)}
function words(ar){return String(ar||'').replace(/[.،؟!?؛:]/g,'').split(/\s+/).filter(Boolean)}
const css=document.createElement('style');css.textContent=`
#courseModal{display:none;position:fixed;z-index:120;inset:0;background:#f5f2ea;overflow:auto}#courseModal.show{display:block}.courseIn{max-width:720px;margin:auto;padding:18px 14px 110px}.courseTop{display:flex;justify-content:space-between;align-items:center;gap:10px}.courseCard{margin-top:16px;background:#fffdf8;border:1px solid #ded9ce;border-radius:28px;padding:22px;box-shadow:0 12px 34px #0000000a}.courseScene{text-align:center;font-size:42px;line-height:1.65;background:#f0eee7;border-radius:22px;padding:18px 8px}.courseArabic{direction:rtl;text-align:center;font:clamp(36px,8vw,54px)/1.8 "Geeza Pro","Noto Naskh Arabic",serif;margin:18px 0}.courseStage{border-top:1px solid #eee7dc;margin-top:15px;padding-top:15px}.courseLabel{font-size:10px;color:#75807c;letter-spacing:.08em;text-transform:uppercase}.courseEn{font-size:21px;font-weight:760;margin-top:6px}.courseJa{font-size:12px;color:#75807c;margin-top:4px}.courseWords{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px;direction:rtl}.courseWord{border:1px solid #ded9ce;background:#fff;border-radius:999px;padding:10px 13px;font:20px "Geeza Pro",serif;cursor:pointer}.courseNext{width:100%;border:0;background:#1f6f61;color:white;border-radius:16px;padding:14px;font-weight:780;margin-top:18px}.courseActions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.courseBtn{border:1px solid #ded9ce;background:#fff;border-radius:14px;padding:10px 12px}.courseProgress{font-size:12px;color:#75807c}.courseChapter{margin-top:14px;background:#20302d;color:#fff;border-radius:22px;padding:16px}.courseChapterTop{display:flex;align-items:center;gap:11px}.courseChapterEmoji{font-size:32px}.courseChapterTitle{font-size:18px;font-weight:800}.courseChapterJa{font-size:12px;color:#cdd7d4;margin-top:2px}.courseChapterStory{font-size:13px;line-height:1.55;color:#e8efed;margin-top:10px}.courseChapterSelect{width:100%;margin-top:12px;border:0;border-radius:12px;padding:10px;background:#fff;color:#20302d;font-weight:700}.courseDots{display:flex;gap:4px;margin-top:10px;overflow:hidden}.courseDot{height:4px;flex:1;background:#ffffff35;border-radius:99px}.courseDot.on{background:#fff}`;document.head.appendChild(css);
const modal=document.createElement('section');modal.id='courseModal';modal.innerHTML='<div class="courseIn"><div class="courseTop"><div><b>Arabic Course</b><div class="courseProgress" id="courseProgress"></div></div><button class="courseBtn" id="courseClose">×</button></div><div id="courseBody"></div></div>';document.body.appendChild(modal);
function howText(x){const map={greet:['A greeting used as a complete social expression.','あいさつとして独立して使える表現です。'],ask_name:['Arabic can ask “what is your name?” without a present-tense copula.','現在形の「〜です」に相当する動詞を置かずに名前を尋ねられます。'],say_name:['A nominal sentence can identify the speaker directly.','名詞文で自分の名前を直接示せます。'],ask_origin:['مِنْ marks source or origin.','مِنْ は出所・起点を表します。'],say_origin:['The prepositional phrase مِنَ الْيَابَانِ works as the predicate.','مِنَ الْيَابَانِ という前置詞句が述語として働きます。']};return map[x.intent]||['Notice how the words combine to express the situation before naming the grammar.','文法名を覚える前に、場面の中で語の組み合わせ方に注目します。']}
function chapterHtml(ch){const opt=chapters.map(c=>`<option value="${c.start-1}" ${c.id===ch.id?'selected':''}>${esc2(c.id)} · ${esc2(c.titleEn)} / ${esc2(c.titleJa)}</option>`).join('');const dots=chapters.map(c=>`<span class="courseDot ${c.id===ch.id?'on':''}"></span>`).join('');return `<section class="courseChapter"><div class="courseChapterTop"><div class="courseChapterEmoji">${esc2(ch.emoji)}</div><div><div class="courseLabel" style="color:#aebfba">${esc2(ch.id)} · Experiences ${ch.start}–${ch.end}</div><div class="courseChapterTitle">${esc2(ch.titleEn)}</div><div class="courseChapterJa">${esc2(ch.titleJa)}</div></div></div><div class="courseChapterStory">${esc2(ch.worldEn)}<br><span style="color:#cdd7d4">${esc2(ch.worldJa)}</span></div><select class="courseChapterSelect" id="courseChapterSelect">${opt}</select><div class="courseDots">${dots}</div></section>`}
function render(){const x=items[ci];if(!x){$q('#courseBody').innerHTML='<div class="courseCard">Course data could not be loaded.</div>';return}const ch=chapterFor(ci);const within=ci+1-ch.start+1;$q('#courseProgress').textContent=`${ch.id} · ${within}/${ch.end-ch.start+1} · Overall ${ci+1}/${items.length}`;let h=chapterHtml(ch)+`<div class="courseCard"><div class="courseLabel">Mental Scene</div><div class="courseScene">${esc2(x.scene)}</div><div class="courseActions"><button class="courseBtn" id="courseListen">▶ Listen first</button></div>`;
if(stage>=1)h+=`<div class="courseStage"><div class="courseLabel">Arabic</div><div class="courseArabic">${esc2(x.ar)}</div><div class="courseActions"><button class="courseBtn" id="courseReplay">▶ Replay</button></div></div>`;
if(stage>=2)h+=`<div class="courseStage"><div class="courseLabel">Meaning</div><div class="courseEn">${esc2(x.en)}</div><div class="courseJa">${esc2(x.ja)}</div></div>`;
if(stage>=3)h+=`<div class="courseStage"><div class="courseLabel">Words · tap to hear</div><div class="courseWords">${words(x.ar).map(w=>`<button class="courseWord" data-course-word="${esc2(w)}">${esc2(w)} 🔊</button>`).join('')}</div></div>`;
if(stage>=4){const t=howText(x);h+=`<div class="courseStage"><div class="courseLabel">How it works</div><div class="courseEn">${esc2(t[0])}</div><div class="courseJa">${esc2(t[1])}</div></div>`}
if(stage>=5)h+=`<div class="courseStage"><div class="courseLabel">Deep Arabic</div><div class="courseEn">Word Anatomy · Root / Pattern · Morphology · Grammar · إعراب</div><div class="courseJa">必要なときだけ深い分析へ進みます。</div><button class="courseBtn" id="courseDeep" style="margin-top:10px">Open Deep Analysis ›</button></div>`;
const labels=['Show Arabic ›','Show meaning ›','Show words ›','How it works ›','Deep Arabic ›','Next Experience ›'];h+=`<button class="courseNext" id="courseNext">${labels[Math.min(stage,5)]}</button><div class="courseActions"><button class="courseBtn" id="coursePrev">‹ Previous</button><button class="courseBtn" id="courseReset">Start this Experience again</button></div></div>`;$q('#courseBody').innerHTML=h;
$q('#courseChapterSelect').onchange=e=>{ci=+e.target.value;stage=0;localStorage.setItem(POS,String(ci));render()};$q('#courseListen').onclick=()=>speak(x.ar,.72);$q('#courseReplay')?.addEventListener('click',()=>speak(x.ar,.72));document.querySelectorAll('[data-course-word]').forEach(b=>b.onclick=()=>speak(b.dataset.courseWord,.68));$q('#courseDeep')?.addEventListener('click',()=>{localStorage.setItem('asl.a1.pos',String(ci));location.href='./living.html'});$q('#courseNext').onclick=()=>{if(stage<5){stage++;render()}else{ci=Math.min(items.length-1,ci+1);stage=0;localStorage.setItem(POS,String(ci));render()}};$q('#coursePrev').onclick=()=>{ci=Math.max(0,ci-1);stage=0;localStorage.setItem(POS,String(ci));render()};$q('#courseReset').onclick=()=>{stage=0;render()};}
async function openCourse(){await ensureData();stage=0;render();modal.classList.add('show')}
$q('#courseClose').onclick=()=>modal.classList.remove('show');
const top=document.querySelector('.top');if(top){const b=document.createElement('button');b.className='btn';b.textContent='Course';b.id='courseOpen';const add=document.querySelector('#add');top.insertBefore(b,add||null);b.onclick=openCourse}
})();