(function(){
const X={
'a1e001':{chain:['greeting intent','fixed idiom','مَرْحَبًا','accusative-looking ending ـًا'],change:[['مَرْحَبًا','Hello / welcome'],['أَهْلًا وَسَهْلًا','Welcome — a different fixed greeting']],noteEn:'Here the safest mental model is not “object → accusative.” The expression is historically analyzable, but synchronically it behaves as a stored greeting.',noteJa:'ここでは「目的語だから対格」と考えない方が安全です。歴史的な分析はできますが、現代の運用では定型挨拶として一まとまりです。'},
'a1e002':{chain:['ask identity','مَا = unknown WHAT','اِسْم + كَ = your name','اِسْمُكَ = nominative nominal pivot'],change:[['مَا اسْمُكَ؟','What is your name?'],['مَا اسْمُهُ؟','What is his name?'],['مَا اسْمُهَا؟','What is her name?']],noteEn:'The possessive suffix changes the person without rebuilding the sentence. This is one reason suffix pronouns are structurally important in Arabic.',noteJa:'所有接尾辞だけを変えると、文の骨格を保ったまま人物を変えられます。接尾代名詞が重要なのはこのためです。'},
'a1e003':{chain:['topic','اِسْمِي = my name','خبر = عَلِيّ','present nominal sentence → no overt “is”'],change:[['اِسْمِي عَلِيّ.','My name is Ali.'],['اِسْمُهُ عَلِيّ.','His name is Ali.'],['اِسْمُهَا مَرْيَمُ.','Her name is Maryam.']],noteEn:'Arabic encodes the relation by juxtaposition in the present. English inserts a copula; Arabic does not need to.',noteJa:'現在の名詞文では、アラビア語は並置そのものが関係を作ります。英語は copula を入れますが、アラビア語では不要です。'},
'a1e004':{chain:['source relation','مِنْ = from','أَيْنَ = where','مِنْ أَيْنَ = from where'],change:[['مِنْ أَيْنَ أَنْتَ؟','Where are you from?'],['أَيْنَ أَنْتَ؟','Where are you?']],noteEn:'Removing مِنْ does not merely shorten the sentence; it changes the semantic relation from origin/source to location.',noteJa:'مِنْ を外すと単に短くなるのではなく、「出身・起点」から「現在位置」へ意味関係そのものが変わります。'},
'a1e005':{chain:['مِنْ','governs following noun','الْيَابَانِ → genitive','whole PP = خبر'],change:[['أَنَا مِنَ الْيَابَانِ.','I am from Japan.'],['أَنَا فِي الْيَابَانِ.','I am in Japan.']],noteEn:'Case is caused locally by the preposition, while the whole prepositional phrase serves a larger sentence role as predicate.',noteJa:'格は前置詞が局所的に引き起こします。一方、前置詞句全体は文の中で述語という大きな役割を持ちます。'},
'a1e006':{chain:['noun 1 = مضاف','noun 2 = مضاف إليه','noun 2 → genitive','definiteness flows from second noun'],change:[['صَبَاحُ الْخَيْرِ','good morning'],['بَابُ الْبَيْتِ','the door of the house'],['مِفْتَاحُ الْبَابِ','the key of the door']],noteEn:'إضافة is not just “of.” It is a noun-to-noun construction with its own rules about definiteness, articles, and case.',noteJa:'إضافة は単なる「of」の翻訳ではなく、定性・冠詞・格に独自の規則を持つ名詞＋名詞構造です。'},
'a1e007':{chain:['speaker referent','gender/number features','predicate adjective agrees','جَاهِزٌ ↔ جَاهِزَةٌ'],change:[['أَنَا جَاهِزٌ.','I am ready. — male speaker'],['أَنَا جَاهِزَةٌ.','I am ready. — female speaker']],noteEn:'English keeps “ready” unchanged. Arabic lets morphology carry information about the referent.',noteJa:'英語の ready は変わりませんが、アラビア語は語形そのものに指示対象の情報を持たせます。'},
'a1e008':{chain:['unknown = location','predicate slot questioned','أَيْنَ moves to focus','الْمِفْتَاحُ stays the known entity'],change:[['الْمِفْتَاحُ عَلَى الْكُرْسِيِّ.','The key is on the chair.'],['أَيْنَ الْمِفْتَاحُ؟','Where is the key?']],noteEn:'A useful model is “replace the known location predicate with أَيْنَ.” This connects statements and questions structurally.',noteJa:'「既知の場所述語を أَيْنَ に置き換える」と考えると、平叙文と疑問文を同じ構造として理解できます。'},
'a1e009':{chain:['عَلَى = spatial relation','preposition governs noun','الْكُرْسِيِّ → genitive','PP as a whole = خبر'],change:[['عَلَى الْكُرْسِيِّ','on the chair'],['فِي الْغُرْفَةِ','in the room'],['تَحْتَ الْكُرْسِيِّ','under the chair']],noteEn:'Do not memorize the kasra in isolation. Ask “what caused this ending?” The answer is the governing relation immediately upstream.',noteJa:'カスラだけを孤立して暗記せず、「この語尾を何が引き起こしたか」を上流へたどるのが重要です。'},
'a1e010':{chain:['gratitude intent','verbal noun شُكْر','fixed accusative form شُكْرًا','independent speech act'],change:[['شُكْرًا.','Thank you.'],['شُكْرًا جَزِيلًا.','Thank you very much.']],noteEn:'جَزِيلًا expands the intensity of the gratitude while matching the accusative form in the conventional expression.',noteJa:'جَزِيلًا を加えると感謝の強さを広げ、定型表現内で対格形として対応します。'}
};
function esc2(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const style=document.createElement('style');style.textContent='.lens{margin-top:14px}.lens h4{margin:16px 0 8px}.causeFlow{display:flex;gap:6px;align-items:center;overflow:auto;padding:8px 0}.causeNode{flex:0 0 auto;background:#eef6f3;border:1px solid #d4e7e1;border-radius:12px;padding:8px 10px;font-size:12px}.arrow{color:#73807c}.transform{border-top:1px solid #eee7dc;padding:10px 0}.transformAr{font:23px/1.5 "Geeza Pro","Noto Naskh Arabic",serif;direction:rtl;text-align:right}.whyBox{background:#fbfaf6;border:1px solid #ebe5d9;border-radius:15px;padding:12px;margin-top:10px}.labelTiny{font-size:10px;color:#73807c;text-transform:uppercase;letter-spacing:.08em}';document.head.appendChild(style);
const old=window.renderGrammar||renderGrammar;
window.renderGrammar=renderGrammar=function(e,b){old(e,b);const x=X[e.id];if(!x)return;const host=document.createElement('div');host.className='lens';host.innerHTML=`<h4>Grammar Lens</h4><div class="labelTiny">Cause → form → role</div><div class="causeFlow">${x.chain.map((n,k)=>`${k?'<span class="arrow">→</span>':''}<span class="causeNode">${esc2(n)}</span>`).join('')}</div><div class="whyBox"><b>Why this matters</b><div>${esc2(x.noteEn)}</div><div class="secondary">${esc2(x.noteJa)}</div></div><h4>Change one piece</h4>${x.change.map(r=>`<div class="transform"><div class="transformAr">${esc2(r[0])}</div><div>${esc2(r[1])}</div></div>`).join('')}`;b.appendChild(host)};
})();