(function(){
let activeWord=null,stage=0;
function currentSentence(){try{return typeof s==='function'?s():null}catch(e){return null}}
function wordById(id){return currentSentence()?.words?.find(w=>w.id===id)||null}
function x(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function objRows(o){if(!o||typeof o!=='object'||!Object.keys(o).length)return '<div class="pwmute">No additional data.</div>';return Object.entries(o).map(([k,v])=>`<div class="pwrow"><span>${x(k)}</span><b>${x(typeof v==='object'?JSON.stringify(v):v)}</b></div>`).join('')}
function familyHtml(w){const a=w.wordFamily||[];if(!a.length)return '<div class="pwmute">No word-family data.</div>';return `<div class="pwfamily">${a.map(f=>`<div class="pwfam"><div class="pwarSmall">${x(f.vocalized||f.word||'')}</div><b>${x(f.meaning?.en||f.meaningEn||'')}</b><div class="pwja">${x(f.meaning?.ja||f.meaningJa||'')}</div><div class="pwmute">${x(f.relationToCurrentWord||f.familyRelation||'')}</div></div>`).join('')}</div>`}
function speakAgain(){if(!activeWord)return;const t=activeWord.ttsText||activeWord.vocalized||activeWord.surface||'';if(!t)return;window.ARABIC_AUDIO_SERVICE?.speak?.(t,{rate:.72})}
const style=document.createElement('style');style.textContent=`
#pwSheet{display:none;position:fixed;z-index:80;left:0;right:0;bottom:0;max-height:76vh;overflow:auto;background:#fffdf8;border-radius:26px 26px 0 0;padding:18px 18px calc(22px + env(safe-area-inset-bottom));box-shadow:0 -16px 50px #0003}#pwSheet.show{display:block}@media(min-width:720px){#pwSheet{left:50%;width:700px;transform:translateX(-50%)}}
.pwtop{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.pwar{direction:rtl;font:38px/1.55 "Geeza Pro","Noto Naskh Arabic",serif}.pwarSmall{direction:rtl;font:23px/1.45 "Geeza Pro","Noto Naskh Arabic",serif}.pwstage{margin-top:15px;border-top:1px solid #eee7dc;padding-top:14px}.pwlabel{font-size:10px;letter-spacing:.08em;text-transform:uppercase;color:#75807c}.pwen{font-size:19px;font-weight:780;margin-top:5px}.pwja{font-size:12px;color:#75807c;margin-top:4px}.pwmute{font-size:12px;color:#75807c}.pwrow{display:grid;grid-template-columns:120px 1fr;gap:10px;padding:8px 0;border-bottom:1px solid #eee7dc;font-size:13px}.pwactions{position:sticky;bottom:0;background:#fffdf8;padding-top:14px;display:flex;gap:8px}.pwnext{flex:1;background:#1f6f61;color:#fff;border:1px solid #1f6f61;border-radius:14px;padding:12px 14px;font-weight:750}.pwsecondary{background:#fff;border:1px solid #ded9ce;border-radius:14px;padding:12px 14px}.pwfamily{display:flex;gap:8px;overflow:auto;padding:3px 0}.pwfam{min-width:150px;border:1px solid #ded9ce;border-radius:14px;padding:10px;background:#fff}`;document.head.appendChild(style);
const sh=document.createElement('section');sh.id='pwSheet';sh.innerHTML='<div id="pwBody"></div>';document.body.appendChild(sh);
function render(){if(!activeWord)return;const w=activeWord;let body=`<div class="pwtop"><div><div class="pwlabel">Listen first</div><div class="pwar">${x(w.vocalized||w.surface)}</div><div class="pwmute">First, only listen. Meaning stays hidden until you press Next.<br>まず音だけ。意味は Next を押すまで表示しません。</div></div><button class="pwsecondary" id="pwClose">×</button></div>`;
if(stage>=1)body+=`<div class="pwstage"><div class="pwlabel">1 · Meaning</div><div class="pwen">${x(w.meaning?.en||w.meaningEn||w.meaning||'')}</div><div class="pwja">${x(w.meaning?.ja||w.meaningJa||'')}</div></div>`;
if(stage>=2)body+=`<div class="pwstage"><div class="pwlabel">2 · Identity</div><div class="pwrow"><span>Lemma</span><b class="pwarSmall">${x(w.lemmaVocalized||w.lemma||'—')}</b></div><div class="pwrow"><span>Root</span><b>${x(w.root||'—')}</b></div><div class="pwrow"><span>Part of speech</span><b>${x(w.partOfSpeech?.en||w.pos||'—')}</b></div>${w.partOfSpeech?.ja?`<div class="pwja">${x(w.partOfSpeech.ja)}</div>`:''}</div>`;
if(stage>=3)body+=`<div class="pwstage"><div class="pwlabel">3 · Morphology / Pattern</div>${objRows(w.morphology)}${w.pattern&&Object.keys(w.pattern).length?`<div style="margin-top:10px">${objRows(w.pattern)}</div>`:''}</div>`;
if(stage>=4)body+=`<div class="pwstage"><div class="pwlabel">4 · إعراب</div>${objRows(w.irab)}</div>`;
if(stage>=5)body+=`<div class="pwstage"><div class="pwlabel">5 · Word Family</div>${familyHtml(w)}</div>`;
if(stage>=6)body+=`<div class="pwstage"><div class="pwlabel">6 · Explanation</div><div>${x(w.explanation?.en||'No further explanation in this item.')}</div><div class="pwja">${x(w.explanation?.ja||'')}</div></div>`;
const labels=['Meaning →','Lemma / Root →','Morphology →','إعراب →','Word Family →','Explanation →','Done'];body+=`<div class="pwactions"><button class="pwsecondary" id="pwReplay">▶︎ Replay</button><button class="pwnext" id="pwNext">${labels[Math.min(stage,6)]}</button></div>`;document.querySelector('#pwBody').innerHTML=body;document.querySelector('#pwClose').onclick=()=>sh.classList.remove('show');document.querySelector('#pwReplay').onclick=speakAgain;document.querySelector('#pwNext').onclick=()=>{if(stage<6){stage++;render()}else sh.classList.remove('show')};}
document.addEventListener('click',function(ev){const el=ev.target.closest?.('.word[data-w]');if(!el)return;const w=wordById(el.dataset.w);if(!w)return;ev.preventDefault();ev.stopPropagation();ev.stopImmediatePropagation();activeWord=w;stage=0;render();sh.classList.add('show');},true);
})();