(function(){
'use strict';
const items=window.FSLMaterialEngine.getByLevel('A1');
const $=id=>document.getElementById(id);
let index=Math.max(0,items.findIndex(x=>x.id===window.FSLStorage.load().progress.currentId));
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function renderWords(item){$('words').innerHTML=(item.words||[]).map((w,i)=>`<button class="word" data-word="${i}">${esc(w.surface)}</button>`).join('')||'<p class="muted">No word analysis yet.</p>';$('wordDetail').className='detail muted';$('wordDetail').textContent='Tap a word to inspect it.';document.querySelectorAll('[data-word]').forEach(b=>b.onclick=()=>showWord(item,Number(b.dataset.word)))}
function showWord(item,i){const w=item.words[i];if(!w)return;const form=w.form?`${w.form.mood||''} ${w.form.tense||''} ${w.form.person||''}${w.form.number?' '+w.form.number:''}`.trim():'';const bits=[`lemma: ${w.lemma||'—'}`,`part of speech: ${w.pos||'—'}`,w.gender?`gender: ${w.gender}`:'',w.number?`number: ${w.number}`:'',form?`form: ${form}`:'',w.role?`role: ${w.role}`:'',w.note?`note: ${w.note}`:''].filter(Boolean);$('wordDetail').className='detail';$('wordDetail').innerHTML=`<strong>${esc(w.surface)}</strong><br>${bits.map(esc).join('<br>')}`;window.FSLAudio.speakWord(w.surface)}
function render(){const item=items[index];if(!item)return;$('scene').textContent=(item.scene||'').replaceAll('-',' · ');$('counter').textContent=`${index+1} / ${items.length}`;$('situation').textContent=item.situation||'';$('sentence').textContent=item.fr;$('en').textContent=item.en;$('ja').textContent=item.ja;$('chunks').innerHTML=(item.chunks||[]).map(c=>`<div class="chunk"><strong>${esc(c.text)}</strong><div>${esc(c.en||'')}</div><div class="small">${esc(c.ja||'')}</div></div>`).join('')||'<p class="muted">No chunks yet.</p>';$('architecture').innerHTML=(item.architecture||[]).map(a=>`<div class="arch">${esc(typeof a==='string'?a:JSON.stringify(a))}</div>`).join('')||'<p class="muted">No structure analysis yet.</p>';$('sound').innerHTML=item.sound?.ipa?`<div class="arch"><strong>IPA</strong><br>/${esc(item.sound.ipa)}/</div>`:'<p class="muted">Sound notes will be added progressively. Audio remains available now.</p>';$('social').innerHTML=item.socialMeaning?Object.entries(item.socialMeaning).map(([k,v])=>`<div class="arch"><strong>${esc(k)}</strong><br>${esc(v)}</div>`).join(''):'<p class="muted">No special social note for this sentence.</p>';renderWords(item);$('dots').innerHTML=items.map((_,i)=>`<span class="dot ${i===index?'active':''}"></span>`).join('');$('prev').disabled=index===0;$('next').disabled=index===items.length-1;window.FSLStorage.setCurrent(item.id)}
$('prev').onclick=()=>{if(index>0){index--;render()}};$('next').onclick=()=>{if(index<items.length-1){index++;render()}};$('play').onclick=()=>window.FSLAudio.speakSentence(items[index].fr);$('slow').onclick=()=>window.FSLAudio.speakSlow(items[index].fr);$('sentence').onclick=()=>window.FSLAudio.speakSentence(items[index].fr);document.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')$('prev').click();if(e.key==='ArrowRight')$('next').click()});render();
if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});
})();
